#!/bin/sh
./gradlew \
  clean shadowJar docker dockerPush darkDeploy test switchDeployments \
  -DstepperHost=hashbang.arctair.com \
  -DstepperBasePath=stepper \
  -DtargetHost=hashbang.arctair.com \
  -DtargetBasePath=api-dark \
  -Dhashbang_baseUrl=http://hashbang.arctair.com/api-dark
