#!/bin/sh
./gradlew \
  clean shadowJar docker dockerPush darkDeploy test switchDeployments \
  -DstepperBaseUri=https://hashbang.arctair.com/stepper \
  -DtargetBaseUri=https://hashbang.arctair.com/hashbang-dark
